#pragma once

#define MOVE_FORWARD 'W'
#define MOVE_BACKWARD 'S'
#define STRAFE_LEFT 'A'
#define STRAFE_RIGHT 'D'
#define JUMP_UP 0x20
#define DUCK 0x11
#define TAB 0x09
#define TRANSLATE_SELECTED_OBJECT 'V'
#define ROTATE_SELECTED_OBJECT 'C'
#define SCALE_SELECTED_OBJECT 'B'
#define CURRENT_AXIS_IS_Z 'Z'
#define CURRENT_AXIS_IS_Y 'Y'
#define CURRENT_AXIS_IS_X 'X'
#define ADD_CUBE3D_TO_PLANE 'E'
#define REMOVE_CUBE3D 0x2E
#define TOOGLE_CONSOLE 0xC0